import './styles/theme.css';

const topics = ['Account or Access Issue','Purchase or Payment','Content or Download','Technical Issue','Refund or Return Request','Collaboration / Business Inquiry','General Question','Other'];
const faqs = [['What kind of content does Arcana offer?','Music, spiritual coaching, digital content, masterclasses, and community drops.'],['How long does support take?','We respond within 1–3 business days and confirm immediately.'],['What is the refund policy?','Digital products are non-refundable once accessed. Damaged physical merchandise may be returned within 14 days.']];
const app = document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML = `<nav><a class="brand" href="#top">Arc<span>∴</span>na</a><ul><li><a href="#faq">FAQ</a></li><li><a href="#contact">Contact</a></li></ul></nav><main id="top"><section class="hero"><p class="eyebrow">The Sanctuary of Support</p><h1>We Got<br><em>Your Back</em></h1><p class="sub">“Every soul that comes to us leaves with answers.”</p><p class="intro">This is not a helpdesk. This is a covenant. Speak plain and receive the weight of truth with the precision of purpose.</p><a class="button" href="#contact">Submit a Request</a></section><section id="faq"><p class="eyebrow">Frequently Asked</p><h2>Questions &amp; Answers</h2><div class="faq">${faqs.map(([q,a],i)=>`<article><button aria-expanded="false" aria-controls="answer-${i}">${q}<span>⌄</span></button><div id="answer-${i}" class="answer">${a}</div></article>`).join('')}</div></section><section id="contact"><p class="eyebrow">Direct Line</p><h2>Reach the Collective</h2><div class="contact"><p class="intro">Real people read every submission. Real answers follow.<br>support@arcana-brand.com</p><form id="support-form" novalidate><label>First name *<input name="fname" required></label><label>Email address *<input name="email" type="email" required></label><label>Subject *<select name="subject" required><option value="">Select a topic</option>${topics.map(t=>`<option>${t}</option>`).join('')}</select></label><label>Order / reference<input name="order" placeholder="ARC-20260001"></label><label>Message *<textarea name="message" required minlength="20"></textarea></label><input name="website" class="honeypot" tabindex="-1" autocomplete="off"><button class="button" type="submit">Send Your Request</button><p id="status" role="status"></p></form></div></section></main><footer>Arc∴na · Ancient soul. Street truth. Cinematic vision.</footer>`;

document.querySelectorAll<HTMLButtonElement>('.faq button').forEach(button => button.addEventListener('click', () => { const open = button.getAttribute('aria-expanded') === 'true'; document.querySelectorAll<HTMLButtonElement>('.faq button').forEach(b => b.setAttribute('aria-expanded','false')); document.querySelectorAll<HTMLElement>('.answer').forEach(a => a.classList.remove('open')); if (!open) { button.setAttribute('aria-expanded','true'); button.nextElementSibling?.classList.add('open'); } }));

document.querySelector<HTMLFormElement>('#support-form')!.addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget as HTMLFormElement; const status = document.querySelector<HTMLParagraphElement>('#status')!; const data = Object.fromEntries(new FormData(form).entries()) as Record<string,string>; const errors: string[] = []; if (!data.fname?.trim()) errors.push('First name is required.'); if (!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(data.email ?? '')) errors.push('Enter a valid email.'); if (!data.subject) errors.push('Choose a subject.'); if (data.order && !/^ARC-\\d{8}$/.test(data.order.toUpperCase())) errors.push('Order references use ARC-YYYYXXXX.'); if ((data.message ?? '').trim().length < 20) errors.push('Give us enough detail to investigate.'); if (data.website) errors.push('Automated submissions are not accepted.'); if (errors.length) { status.textContent = errors.join(' '); return; } const button = form.querySelector<HTMLButtonElement>('button[type=submit]')!; button.disabled = true; button.textContent = 'Sending…'; try { const response = await fetch('/api/webhook-handler', { method: 'POST', headers: {'content-type':'application/json'}, body: JSON.stringify(data) }); if (!response.ok) throw new Error('gateway'); form.innerHTML = '<div class="success"><h3>Received &amp; Sealed</h3><p>Your message has entered the collective. Hold your ground.</p></div>'; } catch { button.disabled = false; button.textContent = 'Send Your Request'; status.textContent = 'The line is unavailable. Email support@arcana-brand.com directly.'; } });
